#------------------------
# GitHub Actions
#------------------------

    name: GitHub-Actions-Tests
    env:
      APP_NAME: "YDS - Astronomy picture of the day"
      DEPLOY_PACKAGE_NAME: "deploy-ver-${{ github.sha }}"
    
    on:
      push: 
        branches:
          - master
      pull_request:
        branches:
          - master
    
    jobs:
      client_tests:
        runs-on: windows-latest
        defaults:
          run:
            working-directory: ./
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '18'
        - name: Run tests
          run : |
            npm install --save --legacy-peer-deps
            npm run test
